### ISSUE TITLE
Sprint 1 Post-Deliverables

### ISSUE THREAD

**Issue by MattSkinner30** [MattSkinner30/simple-chat-app#12]
@rachel-glennie @ericadamski 

**Your progress so far.**
- [x] General layout
- [x] Users list
- [x] Notifications
- [x] Chat part
- [x] Conceptualizing colours

**All the issues you created (and hopefully completed) for the past deliverable.**
- [x] Competitor Research and chat room trends
- [x] Name the chat
- [x] Decide on the general look of the chat
- [x] Paper Wireframes
- [x] Digital Wireframe

**Anything you found was a positive from the past few weeks minimum of 2.**
I really like the simplicity of our design.
I managed to create a gradient that doesn't look like garbage.

**Anything you found didn't work out so well from the past few weeks**
We tend to procrastinate.
Still not loving how the notifications look.

**Ask @ericadamski for feedback on a part of your project. minimum of 1**
What do you think about how the notifications appear (location, style, etc;).
Also, do you think that the text sizes are appropriate in the different sections. 
I have attached a screenshot for reference. 

![dat-chat-wireframe](https://cloud.githubusercontent.com/assets/10464637/22527937/11cf3ee8-e89f-11e6-9198-5cffd140d19e.png)

**Comment by rachel-glennie** [comment]
# Created Issues:
- [x] Research competitors.
- [x] Name and theme the chat
- [x] Paper wireframes
- [x] Refine detail within the wireframe
- [x] Decide on general design/colours
- [x] Illustrator mockup

**Comment by rachel-glennie** [comment]
# Positive
I'm really happy with the wireframe and colour scheme! The simplicity is something I really appreciate about it. Also Matt is a gradient master.

# Negative
The wireframe needs some more detail and finishing touches. But that's the point of a wireframe! :star:

# Feedback
@ericadamski - Do you think that we're missing any key features that should be included in our chat app?

**Comment by ericadamski** [comment]
Awesome work guys! Everything looks great!
